FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
            sudo  \
            curl  \
            wget  \
            git-core  \
            gpg  \
            rlwrap  \
            software-properties-common  \
            unzip curl net-tools lsof
