version: "3.7"

services:

  fiberdb:
    image: experiment.fiber.db
    build:
      context: ./datomicfree
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    depends_on:
      - base2

  db:
    image: experiment.fiber.db
    volumes:
      - ../../:/opt/root
      - ./datomicfree:/opt/app
      - type: volume
        source:  experiment.fiber.stage1.db
        target: /opt/datomic-data
        volume:
          nocopy: true
    # ports:
      # - 4436:4336
      # - 4435:4335
      # - 4434:4334
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/free-transactor.properties
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    depends_on:
      - fiberdb


volumes:
  experiment.fiber.stage1.db:
    name: experiment.fiber.stage1.db