version: "3.2"

services:

  db:
    image: seeris/fiber.db:dev
    volumes:
      - type: volume
        source:  fiber.db
        target: /opt/datomic-data
        volume:
          nocopy: true
    command: ./bin/transactor ./config/free-transactor.properties

  app:
    image: seeris/fiber.app
    build:
      context: ../src/stage1/app
      dockerfile: ./prod.Dockerfile
    ports:
      - 4500:8080
      - 4554:7878
    command: bash c main
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
  ui:
    image: seeris/fiber.ui
    build:
      context: ../src/stage1/ui
      dockerfile: ./prod.Dockerfile
    ports:
      - 4600:9500
    command: bash c main
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
volumes:
  fiber.db:
