version: "3.2"

services:

  app:
    image: seeris/fiber.app
    volumes:
      - ../src/stage1/app:/opt/app
      - ../../fiber.data:/opt/data
      - ../:/opt/root
    build:
      context: ../src/stage1/app
      dockerfile: ./Dockerfile
    ports:
      - 4554:7878
      - 4500:8080
    # command: bash c dev
    command: tail -f /dev/null
    environment:
      - STAGE=dev
    depends_on:
      - base2
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
  ui:
    image: seeris/fiber.ui
    volumes:
      - ../src/stage1/ui:/opt/app
      - ../:/opt/root
    build:
      context: ../src/stage1/ui
      dockerfile: ./Dockerfile
    ports:
      - 4664:7888
      - 4600:9500
      - 9630:9630
    # command: bash c main
    command: tail -f /dev/null
    environment:
      - STAGE=dev
    depends_on:
      - base2
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

volumes:
  fiber.stage1.db:
