version: "3.7"

services:

  app:
    image: playground.fiber.app
    volumes:
      - ../src/stage1/app:/opt/app
      - ../../playground.fiber.data:/opt/data
      - ../:/opt/root
    build:
      context: ../src/stage1/app
      dockerfile: ./Dockerfile
    ports:
      - 7788:7788
      - 4500:8080
    # command: bash f dev
    command: tail -f /dev/null
    environment:
      - STAGE=dev
    depends_on:
      - base2
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
  ui:
    image: playground.fiber.ui
    volumes:
      - ../src/stage1/ui:/opt/app
      - ../:/opt/root
    build:
      context: ../src/stage1/ui
      dockerfile: ./Dockerfile
    ports:
      - 8899:8899
      - 4600:9500
      - 9630:9630
    # command: bash f main
    command: tail -f /dev/null
    environment:
      - STAGE=dev
    depends_on:
      - base2
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
